### ISSUE TITLE
部分未定义，博客标签打不开

### ISSUE THREAD

**Issue by CosmosK** [forsigner/fexo#110]
Unhandled rejection ReferenceError: G:\Fexo\themes\fexo\layout\archive.ejs:5
    3|
    4|   <div class="post-list-box archive-body">
 >> 5|     <%- getPostListsDom(page.posts) %>
    6|   </div>
    7|
    8|   <div class="archive-footer">

partial is not defined
    at eval (eval at <anonymous> (G:\Fexo\node_modules\hexo-renderer-ejs\node_modules\ejs\lib\ejs.js:549:12), <anonymous>:103:12)
    at Array.forEach (native)
    at getPostListsDom (eval at <anonymous> (G:\Fexo\node_modules\hexo-renderer-ejs\node_modules\ejs\lib\ejs.js:549:12), <anonymous>:101:9)
    at eval (eval at <anonymous> (G:\Fexo\node_modules\hexo-renderer-ejs\node_modules\ejs\lib\ejs.js:549:12), <anonymous>:14:17)
这是错误信息。

**Comment by forsigner** [comment]
@CosmosK 抱歉回复晚了 请问这问题还有吗？
