### ISSUE TITLE
遇到几个小问题^_^

### ISSUE THREAD

**Issue by imbyron** [forsigner/fexo#6]
1、超过四个字的博客名就会换行
2、改了page_nav的配置，但是面包屑不会跟着变。
3、关于页面的宽度希望可以调整
4、盒子这个图标是否可以点击到首页，现在似乎没有回到首页的地方。
5、只配置了disqus评论，多说评论的js也会加载。

**Comment by forsigner** [comment]
@imbyron 145解决了，3的话你用 `hexo server` 确认一下是否是不会变，关于页面宽度是指文章列表还是文章内容？

**Comment by Kiritoalex** [comment]
你好！我也遇到了一个问题，就是使用移动设备时，比较长的文章名会超过屏幕，可能是对于移动设备的字体的设定有点问题。然后就是移动设备看不到 盒子 ，也就是说想访问友链之类的找不到入口来进入

**Comment by forsigner** [comment]
移动端问题还比较多，我这几天在改善中

**Comment by imbyron** [comment]
@forsigner 不是文章，是关于（about）页面的宽度。

**Comment by imbyron** [comment]
还有：盒子里面的链接可不可以新页面打开。
比如我做了一个外链，希望新页面打开。

**Comment by idisfkj** [comment]
你好，我在hexo s 的时候能正常开启服务 输入localhost:4000 也能正常进入 但是 会有如下问题：
ps：虽然也能正常使用 但每次看到这个就想消灭它
```
ERROR Process failed: layout/.DS_Store
TypeError: Cannot read property 'compile' of undefined
    at View._precompile (/Users/idisfkj/blog/node_modules/hexo/lib/theme/view.js:104:22)
    at View (/Users/idisfkj/blog/node_modules/hexo/lib/theme/view.js:13:8)
    at new Theme._View.View (/Users/idisfkj/blog/node_modules/hexo/lib/theme/index.js:37:10)
    at Theme.setView (/Users/idisfkj/blog/node_modules/hexo/lib/theme/index.js:71:20)
    at /Users/idisfkj/blog/node_modules/hexo/lib/theme/processors/view.js:14:14
    at tryCatcher (/Users/idisfkj/blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/idisfkj/blog/node_modules/bluebird/js/release/promise.js:503:31)
    at Promise._settlePromise (/Users/idisfkj/blog/node_modules/bluebird/js/release/promise.js:560:18)
    at Promise._settlePromise0 (/Users/idisfkj/blog/node_modules/bluebird/js/release/promise.js:605:10)
    at Promise._settlePromises (/Users/idisfkj/blog/node_modules/bluebird/js/release/promise.js:684:18)
    at Promise._fulfill (/Users/idisfkj/blog/node_modules/bluebird/js/release/promise.js:629:18)
    at Promise._resolveCallback (/Users/idisfkj/blog/node_modules/bluebird/js/release/promise.js:424:57)
    at Promise._settlePromiseFromHandler (/Users/idisfkj/blog/node_modules/bluebird/js/release/promise.js:515:17)
    at Promise._settlePromise (/Users/idisfkj/blog/node_modules/bluebird/js/release/promise.js:560:18)
    at Promise._settlePromise0 (/Users/idisfkj/blog/node_modules/bluebird/js/release/promise.js:605:10)
    at Promise._settlePromises (/Users/idisfkj/blog/node_modules/bluebird/js/release/promise.js:684:18)
    at Promise._fulfill (/Users/idisfkj/blog/node_modules/bluebird/js/release/promise.js:629:18)
    at /Users/idisfkj/blog/node_modules/bluebird/js/release/nodeback.js:42:21
    at /Users/idisfkj/blog/node_modules/graceful-fs/graceful-fs.js:78:16
    at tryToString (fs.js:414:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)
ERROR Process failed: layout/_partial/.DS_Store
TypeError: Cannot read property 'compile' of undefined
    at View._precompile (/Users/idisfkj/blog/node_modules/hexo/lib/theme/view.js:104:22)
    at View (/Users/idisfkj/blog/node_modules/hexo/lib/theme/view.js:13:8)
    at new Theme._View.View (/Users/idisfkj/blog/node_modules/hexo/lib/theme/index.js:37:10)
    at Theme.setView (/Users/idisfkj/blog/node_modules/hexo/lib/theme/index.js:71:20)
    at /Users/idisfkj/blog/node_modules/hexo/lib/theme/processors/view.js:14:14
    at tryCatcher (/Users/idisfkj/blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/idisfkj/blog/node_modules/bluebird/js/release/promise.js:503:31)
    at Promise._settlePromise (/Users/idisfkj/blog/node_modules/bluebird/js/release/promise.js:560:18)
    at Promise._settlePromise0 (/Users/idisfkj/blog/node_modules/bluebird/js/release/promise.js:605:10)
    at Promise._settlePromises (/Users/idisfkj/blog/node_modules/bluebird/js/release/promise.js:684:18)
    at Promise._fulfill (/Users/idisfkj/blog/node_modules/bluebird/js/release/promise.js:629:18)
    at Promise._resolveCallback (/Users/idisfkj/blog/node_modules/bluebird/js/release/promise.js:424:57)
    at Promise._settlePromiseFromHandler (/Users/idisfkj/blog/node_modules/bluebird/js/release/promise.js:515:17)
    at Promise._settlePromise (/Users/idisfkj/blog/node_modules/bluebird/js/release/promise.js:560:18)
    at Promise._settlePromise0 (/Users/idisfkj/blog/node_modules/bluebird/js/release/promise.js:605:10)
    at Promise._settlePromises (/Users/idisfkj/blog/node_modules/bluebird/js/release/promise.js:684:18)
    at Promise._fulfill (/Users/idisfkj/blog/node_modules/bluebird/js/release/promise.js:629:18)
    at /Users/idisfkj/blog/node_modules/bluebird/js/release/nodeback.js:42:21
    at /Users/idisfkj/blog/node_modules/graceful-fs/graceful-fs.js:78:16
    at tryToString (fs.js:414:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)
INFO  Hexo is running at http://localhost:4000/. Press Ctrl+C to stop.

```
这个应该怎么消除呢？

**Comment by imbyron** [comment]
2，我已经确认了，看下图，我的链接是archives，配置里写的是归档，但是面包屑显示的是“博客”
![](http://ww1.sinaimg.cn/large/0068QGxkjw1f1jymsnze1j30de07bmxm.jpg)

**Comment by idisfkj** [comment]
你好！favicon.ico 如何显示，我把favicon.ico放在了source目录下  为何没有效果

**Comment by imbyron** [comment]
还有一个关于评论的问题，我就不新开issues了。
就是关于页面以及链接页面评论不能正常显示。
我已经打开了页面里面的评论开关。
事实上，生成的html代码里面已经包含了js脚本，我怀疑是链接的问题。
正常的文章页面，disqus代码里面显示的是`disqus_url = 'http://{my_site_url}/2015/06/24/some-note-1/';`
关于、链接等页面，显示的是`disqus_url = '{my_site_url}/about/index.html`

**Comment by imbyron** [comment]
@idisfkj 你放在hexo的source里面试试。

**Comment by forsigner** [comment]
@imbyron 可以配置成新页面打开了，你pull 最新代码看看，可以这样配置：

``` yml
# config page nav
page_nav:
  - name: 博客
    url: /archives/
    target_blank: false # 不在新页面打开
  - name: 分类
    url: /category/
    target_blank: 
  - name: 标签
    url: /tag/
    target_blank: false
  - name: 友链
    url: /link/
    target_blank: false
  - name: 关于
    url: /about/
    target_blank: false
  - name: RSS
    url: /atom.xml
    target_blank: true # 在新页面打开
```

**Comment by forsigner** [comment]
@idisfkj 你的node版本是多少？出现可能跟node版本有关

**Comment by forsigner** [comment]
@imbyron 你说的评论问题搞定了，你试试

**Comment by imbyron** [comment]
@forsigner OK，我这就试试。

**Comment by imbyron** [comment]
@forsigner 你最新的代码是`add hint`啊，这就是最新的么？

**Comment by imbyron** [comment]
@forsigner 我猜你的代码没有push成功。。。

**Comment by forsigner** [comment]
对的 忘记push了 中午回宿舍push.....

**Comment by forsigner** [comment]
@imbyron 最新代码push了

**Comment by imbyron** [comment]
收到，赞。

**Comment by imbyron** [comment]
遇到一个奇怪的问题
1、你做的新效果，放在盒子上，会有图标的转换，hexo server后正常，传到coding上面，这个效果没有了。
2、同时，评论表的好宽，不知是哪里出问题了。
我博客已经换上你的模板了，你可以到我博客上看效果。

**Comment by forsigner** [comment]
应该是coding上的代码没有更为最新的，你确认一下

**Comment by imbyron** [comment]
@forsigner 关于页面和link页面评论框显示了，但是，评论没显示出来，是不是哪里不对？

**Comment by imbyron** [comment]
我看了下生成的HTML代码，应该是
https://github.com/forsigner/fexo/issues/6#issuecomment-191783379
这个问题。

关于页面和链接页面后面`disqus_url`后面都有index.html，普通页面则直接到文件夹。

**Comment by imbyron** [comment]
我在console运行了去掉`index.html`的disqus代码，评论可以显示了，果真是页面后缀多了index.html的原因
···
var disqus_shortname = 'byronblog';
    var disqus_url = 'http://googleyixia.com/about/';
    (function(){
      var dsq = document.createElement('script');
      dsq.type = 'text/javascript';
      dsq.async = true;
      dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
···

怎样在主题里去掉呢？

**Comment by forsigner** [comment]
@imbyron  我看看哈，周末出去玩了，没更新
by the way ，欢迎pull request哦，我个人这段时间比较忙，更新比较慢

**Comment by imbyron** [comment]
哈哈，我先手动在生成的HTML页面修改了。

**Comment by imbyron** [comment]
周末就应该去玩，宅在家里会发霉的。
